### PR TITLE
Suggested fix for issue #59 - Serial tool window exception 

### PR DESCRIPTION
**Pull request by francis95-han**

### CODE REVIEW

**Comment by BrianHenryIE** [comment]
Hey,

I tried to install this but I got the same error:

`java.lang.IllegalStateException: You must not register toolwindow programmatically so early. Rework code or use ToolWindowManager.invokeLater`

My steps:

* Go CLion -> Settings
* Choose Plugins in left menu
* Select Arduino Support and uninstall
* Restart IDE

1. In Terminal, `cd ~/Downloads` `wget https://raw.githubusercontent.com/francis95-han/CLionArduinoPlugin/master/dist/CLionArduinoPlugin.1.5.2_fix59.zip`
2. Open CLion
3. Go CLion -> Settings
4. Choose Plugins in left menu
5. Click setting cog -> Install Plugin from Disk
6. Navigate to Downloads, choose `CLionArduinoPlugin.1.5.2_fix59.zip` and Open
7. Click Restart IDE

**Comment by francis95-han** [comment]
Sorry,It's my question, I upload the wrong zip file ,now it's ok,please try again

**Comment by francis95-han** [comment]
> Hey,
> 
> I tried to install this but I got the same error:
> 
> `java.lang.IllegalStateException: You must not register toolwindow programmatically so early. Rework code or use ToolWindowManager.invokeLater`
> 
> My steps:
> 
> * Go CLion -> Settings
> * Choose Plugins in left menu
> * Select Arduino Support and uninstall
> * Restart IDE
> 
> 1. In Terminal, `cd ~/Downloads` `wget https://raw.githubusercontent.com/francis95-han/CLionArduinoPlugin/master/dist/CLionArduinoPlugin.1.5.2_fix59.zip`
> 2. Open CLion
> 3. Go CLion -> Settings
> 4. Choose Plugins in left menu
> 5. Click setting cog -> Install Plugin from Disk
> 6. Navigate to Downloads, choose `CLionArduinoPlugin.1.5.2_fix59.zip` and Open
> 7. Click Restart IDE
> 
> I disabled the one other plugin I had installed, but same behaviour.
> 
> Can you post the build steps please? It still appears as "1.5.2" in CLion/plugins so I'd like to try change that to be sure it's using the locally uploaded version.


Sorry,It's my question, I upload the wrong zip file ,now it's ok,please try again

**Comment by francis95-han** [comment]
> Hey,
> 
> I tried to install this but I got the same error:
> 
> `java.lang.IllegalStateException: You must not register toolwindow programmatically so early. Rework code or use ToolWindowManager.invokeLater`
> 
> My steps:
> 
> * Go CLion -> Settings
> * Choose Plugins in left menu
> * Select Arduino Support and uninstall
> * Restart IDE
> 
> 1. In Terminal, `cd ~/Downloads` `wget https://raw.githubusercontent.com/francis95-han/CLionArduinoPlugin/master/dist/CLionArduinoPlugin.1.5.2_fix59.zip`
> 2. Open CLion
> 3. Go CLion -> Settings
> 4. Choose Plugins in left menu
> 5. Click setting cog -> Install Plugin from Disk
> 6. Navigate to Downloads, choose `CLionArduinoPlugin.1.5.2_fix59.zip` and Open
> 7. Click Restart IDE
> 
> I disabled the one other plugin I had installed, but same behaviour.
> 
> Can you post the build steps please? It still appears as "1.5.2" in CLion/plugins so I'd like to try change that to be sure it's using the locally uploaded version.

@BrianHenryIE 
Sorry,It's my question, I upload the wrong zip file ,now it's ok,please try again

**Comment by BrianHenryIE** [comment]
Looks good so far. 

Screenshot 2022-12-10 at 8 35 19 PM


Thanks.

**Comment by vsch** [comment]
New version of plugin has this issue fixed. JetBrains should have it approved soon, but there is a direct link to this version before approval: https://plugins.jetbrains.com/plugin/11301-arduino-support/versions/stable/305519.

Works with CLion up to 2022.2. 2022.3 is broken and it will take some work to get it working with it.

**Pull request closed without merging**
